apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: api
          image: k8s-python-api:1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: dev
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
